definitions:
  domain.Club:
    properties:
      address:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  domain.FilterTournament:
    properties:
      id:
        type: string
      isAvalible:
        description: true if tournament is not started and not full
        type: boolean
      name:
        type: string
    type: object
  domain.FilterUser:
    properties:
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
      telegramId:
        type: integer
    type: object
  domain.Loyalty:
    properties:
      description:
        type: string
      discount:
        type: integer
      id:
        type: integer
      name:
        type: string
      requirements:
        type: string
    type: object
  domain.PatchUser:
    properties:
      avatar:
        type: string
      bio:
        type: string
      birthDate:
        type: string
      city:
        type: string
      firstName:
        type: string
      isRegistered:
        type: boolean
      lastName:
        type: string
      padelProfiles:
        type: string
      playingPosition:
        $ref: '#/definitions/domain.PlayingPosition'
      rank:
        type: number
      telegramUsername:
        type: string
    type: object
  domain.PlayingPosition:
    enum:
    - right
    - left
    - both
    type: string
    x-enum-varnames:
    - PlayingPositionRight
    - PlayingPositionLeft
    - PlayingPositionBoth
  domain.Registration:
    properties:
      date:
        type: string
      id:
        type: string
      status:
        $ref: '#/definitions/domain.RegistrationStatus'
      tournament:
        $ref: '#/definitions/domain.Tournament'
      tournamentId:
        type: string
      user:
        $ref: '#/definitions/domain.User'
      userId:
        type: string
    type: object
  domain.RegistrationStatus:
    enum:
    - PENDING
    - ACTIVE
    - CANCELED
    - CANCELED_BY_USER
    type: string
    x-enum-varnames:
    - RegistrationStatusPending
    - RegistrationStatusActive
    - RegistrationStatusCanceled
    - RegistrationStatusCanceledByUser
  domain.Tournament:
    properties:
      club:
        $ref: '#/definitions/domain.Club'
      description:
        type: string
      endTime:
        type: string
      id:
        type: string
      maxUsers:
        type: integer
      name:
        type: string
      organizator:
        $ref: '#/definitions/domain.User'
      participants:
        items:
          $ref: '#/definitions/domain.Registration'
        type: array
      price:
        type: integer
      rankMax:
        type: number
      rankMin:
        type: number
      startTime:
        type: string
      tournamentType:
        type: string
    type: object
  domain.User:
    properties:
      avatar:
        type: string
      bio:
        type: string
      birthDate:
        type: string
      city:
        type: string
      firstName:
        type: string
      id:
        type: string
      isRegistered:
        type: boolean
      lastName:
        type: string
      loyalty:
        $ref: '#/definitions/domain.Loyalty'
      padelProfiles:
        type: string
      playingPosition:
        $ref: '#/definitions/domain.PlayingPosition'
      rank:
        type: number
      telegramId:
        type: integer
      telegramUsername:
        type: string
    type: object
  domain.Waitlist:
    properties:
      date:
        type: string
      id:
        type: integer
      tournament:
        $ref: '#/definitions/domain.Tournament'
      tournamentId:
        type: string
      user:
        $ref: '#/definitions/domain.User'
      userId:
        type: string
    type: object
  image.UploadResponse:
    properties:
      url:
        example: https://example.com/image.jpg
        type: string
    type: object
info:
  contact: {}
  description: Manage chats, users
  title: GoPadel server
  version: "1.0"
paths:
  /images/upload/avatar:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Image data
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: A url to the stored image
          schema:
            $ref: '#/definitions/image.UploadResponse'
        "400":
          description: Parsing error
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Upload file to s3
      tags:
      - images
  /loyalties:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: List of loyalty programs
          schema:
            items:
              $ref: '#/definitions/domain.Loyalty'
            type: array
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Get all loyalty programs
      tags:
      - loyalties
  /registrations/{tournament_id}:
    post:
      consumes:
      - application/json
      description: Creates new registration or updates existing CANCELED status to
        PENDING
      parameters:
      - description: Tournament ID
        in: path
        name: tournament_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Registration created or updated
          schema:
            $ref: '#/definitions/domain.Registration'
        "400":
          description: Invalid request data
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: User not authorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Tournament not found
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict (already registered or tournament full)
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Register for tournament
      tags:
      - registration
  /registrations/{tournament_id}/cancel:
    post:
      consumes:
      - application/json
      description: Cancels registration with PENDING status (before payment)
      parameters:
      - description: Tournament ID
        in: path
        name: tournament_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Registration canceled
          schema:
            $ref: '#/definitions/domain.Registration'
        "400":
          description: Invalid request data
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: User not authorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Registration not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Cancel registration before payment
      tags:
      - registration
  /registrations/{tournament_id}/cancel-paid:
    post:
      consumes:
      - application/json
      description: Cancels registration with ACTIVE status (after payment)
      parameters:
      - description: Tournament ID
        in: path
        name: tournament_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Registration canceled
          schema:
            $ref: '#/definitions/domain.Registration'
        "400":
          description: Invalid request data
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: User not authorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Registration not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Cancel registration after payment
      tags:
      - registration
  /registrations/{tournament_id}/reactivate:
    post:
      consumes:
      - application/json
      description: Reactivates registration from CANCELED_BY_USER status to ACTIVE
      parameters:
      - description: Tournament ID
        in: path
        name: tournament_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Registration reactivated
          schema:
            $ref: '#/definitions/domain.Registration'
        "400":
          description: Invalid request data
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: User not authorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Registration not found
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Tournament is full
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Reactivate canceled registration
      tags:
      - registration
  /registrations/my:
    get:
      consumes:
      - application/json
      description: Returns all registrations for the current user
      produces:
      - application/json
      responses:
        "200":
          description: List of registrations
          schema:
            items:
              $ref: '#/definitions/domain.Registration'
            type: array
        "401":
          description: User not authorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Get my registrations
      tags:
      - registration
  /tournaments/{tournament_id}/participants:
    get:
      consumes:
      - application/json
      description: Get all participants of a tournament with status ACTIVE, PENDING,
        or CANCELED_BY_USER
      parameters:
      - description: Tournament ID
        in: path
        name: tournament_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of tournament participants
          schema:
            items:
              $ref: '#/definitions/domain.Registration'
            type: array
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Tournament not found
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Get tournament participants
      tags:
      - tournaments
  /tournaments/{tournament_id}/waitlist:
    get:
      consumes:
      - application/json
      description: Get list of users in tournament waitlist
      parameters:
      - description: Tournament ID
        in: path
        name: tournament_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Tournament waitlist
          schema:
            items:
              $ref: '#/definitions/domain.Waitlist'
            type: array
        "400":
          description: Invalid tournament ID
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Tournament not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Get tournament waitlist
      tags:
      - tournaments
  /tournaments/filter:
    post:
      consumes:
      - application/json
      parameters:
      - description: Tournament filter
        in: body
        name: filter
        required: true
        schema:
          $ref: '#/definitions/domain.FilterTournament'
      produces:
      - application/json
      responses:
        "200":
          description: List of tournaments
          schema:
            items:
              $ref: '#/definitions/domain.Tournament'
            type: array
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Filter tournaments
      tags:
      - tournaments
  /users/{user_id}/tournaments:
    get:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of tournaments where user participated
          schema:
            items:
              $ref: '#/definitions/domain.Tournament'
            type: array
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Get tournaments by user ID
      tags:
      - users
  /users/filter:
    post:
      consumes:
      - application/json
      parameters:
      - description: User filter
        in: body
        name: filter
        required: true
        schema:
          $ref: '#/definitions/domain.FilterUser'
      produces:
      - application/json
      responses:
        "200":
          description: List of users
          schema:
            items:
              $ref: '#/definitions/domain.User'
            type: array
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Filter users
      tags:
      - users
  /users/me:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: User data
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Get me
      tags:
      - users
    patch:
      consumes:
      - application/json
      parameters:
      - description: User update data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.PatchUser'
      produces:
      - application/json
      responses:
        "200":
          description: Updated user data
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Update current user data
      tags:
      - users
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: User data
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Create me
      tags:
      - users
  /users/me/bio:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: User bio data
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
        "404":
          description: User bio not found
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Get current user bio
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-API-Token
    type: apiKey
swagger: "2.0"
