export enum RegistrationStatus {
  PENDING = "PENDING",
  INVITED = "INVITED",
  CONFIRMED = "CONFIRMED",
  CANCELLED_BEFORE_PAYMENT = "CANCELLED_BEFORE_PAYMENT",
  CANCELLED_AFTER_PAYMENT = "CANCELLED_AFTER_PAYMENT",
  REFUNDED = "REFUNDED",
  CANCELLED = "CANCELLED",
  LEFT = "LEFT",
}
