services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile.api
    ports:
      - "8001:8000"
    volumes:
      - ./:/app
    depends_on:
      - db

  bot:
    build:
      context: ./
      dockerfile: Dockerfile.bot
  
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - gopadel_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  gopadel_data: