services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile.api
    ports:
      - "8001:8000"
    volumes:
      - ./:/app
    depends_on:
      - db

  bot:
    build:
      context: ./
      dockerfile: Dockerfile.bot
    env_file:
      - .env
  
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - gopadel-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer:5
    ports:
      - "8080:8080"

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: --config /etc/nats/nats-server.conf
    env_file:
      - .env
    volumes:
      - ./nats-server.conf:/etc/nats/nats-server.conf

volumes:
  gopadel-db:
