"""user bio

Revision ID: 071ac824d6f7
Revises: b48fe1e71060
Create Date: 2025-05-28 19:50:27.747415

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "071ac824d6f7"
down_revision: Union[str, None] = "b48fe1e71060"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("bio", sa.Text(), nullable=False, server_default="")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "bio")
    # ### end Alembic commands ###
