"""add end_time and description to tournaments

Revision ID: 13c1e0f9326a
Revises: f5d8e2a1b3c9
Create Date: 2025-05-29 22:14:00.849190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c1e0f9326a'
down_revision: Union[str, None] = 'f5d8e2a1b3c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('tournaments', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('tournaments', 'description')
    op.drop_column('tournaments', 'end_time')
    # ### end Alembic commands ###
