"""user model fix

Revision ID: 200c5a93cb67
Revises: 3463160b71de
Create Date: 2025-05-01 21:16:57.070684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '200c5a93cb67'
down_revision: Union[str, None] = '3463160b71de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'loyalty_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'loyalty_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
