"""add_user_id_to_admin_users

Revision ID: 5c9addaa70a5
Revises: 6324aca64b6d
Create Date: 2025-05-25 21:40:06.704470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9addaa70a5'
down_revision: Union[str, None] = '6324aca64b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'admin_users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_users', type_='foreignkey')
    op.drop_column('admin_users', 'user_id')
    # ### end Alembic commands ###
