"""canceled by user status

Revision ID: 7e01fea4f4b4
Revises: 5c9addaa70a5
Create Date: 2025-05-26 11:37:20.405464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e01fea4f4b4'
down_revision: Union[str, None] = '5c9addaa70a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tournaments_organization_id_users'), 'tournaments', type_='foreignkey')
    op.drop_column('tournaments', 'organization_id')
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('tournaments', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_tournaments_organization_id_users'), 'tournaments', 'users', ['organization_id'], ['id'])
    # ### end Alembic commands ###
