"""payments update

Revision ID: c4b1724585b3
Revises: db_uuid_tournament
Create Date: 2025-05-17 20:28:13.693962

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision: str = "c4b1724585b3"
down_revision: Union[str, None] = "db_uuid_tournament"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Add the column as nullable first
    op.add_column(
        "payments", sa.Column("payment_link", sa.String(length=255), nullable=True)
    )

    # 2. Fill existing records with default value
    op.execute(text("UPDATE payments SET payment_link = 'nah'"))

    # 3. Make the column non-nullable
    op.alter_column("payments", "payment_link", nullable=False)

    op.alter_column(
        "registrations", "payment_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "registrations", "payment_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("payments", "payment_link")
    # ### end Alembic commands ###
