"""fix_waitlist_autoincrement

Revision ID: e1ea249d04e6
Revises: f3a4b1d9c8e7
Create Date: 2025-06-03 11:29:00.135713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1ea249d04e6'
down_revision: Union[str, None] = 'f3a4b1d9c8e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waitlists', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('waitlists', 'tournament_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('waitlists', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waitlists', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('waitlists', 'tournament_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('waitlists', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
