services:
  database:
    restart: unless-stopped
    image: postgres:16.7
    container_name: database-go
    volumes:
      - gopadel-server:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: always
    env_file:
      - .env
    ports:
      - "1000:8080"
    depends_on:
      - database

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: --config /etc/nats/nats-server.conf
    env_file:
      - .env
    volumes:
      - ./nats-server.conf:/etc/nats/nats-server.conf

volumes:
  gopadel-server:
