ALTER TABLE users ALTER COLUMN loyalty_id DROP DEFAULT;
ALTER TABLE users ALTER COLUMN rank DROP DEFAULT;
ALTER TABLE users ALTER COLUMN is_registered DROP DEFAULT;

ALTER TABLE users DROP CONSTRAINT ck_users_rank;