name: deploy-server

on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: Deploy to PROD/DEV
        type: choice
        options: [PROD, DEV]
        default: DEV
      migrate:
        required: true
        description: migrate
        type: boolean
        default: false

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    secrets: inherit
    with:
      dockerfile_path: 'server/Dockerfile.api'
      context_path: 'server'
      image_name: 'russianpadel-server'
      environment: ${{ github.event.inputs.environment }}
      secret-service-hash: ${{ github.event.inputs.environment == 'PROD' && 'SERVER_SERVICE_HASH' || 'SERVER_SERVICE_HASH_DEV' }}

  migrate-db:
    uses: ./.github/workflows/migrate.yaml
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    if: ${{ github.event.inputs.migrate == true }}
    needs: deploy
    with:
      image_name: 'russianpadel-server'
      environment: ${{ github.event.inputs.environment }}
      secret-service-hash: ${{ github.event.inputs.environment == 'PROD' && 'MIGRATE_HASH' || 'MIGRATE_HASH_DEV' }}
